### ISSUE TITLE
Tests for solving A @ x == b is wrong

### ISSUE THREAD

**Issue by fumin** [ktye/qr#1]
Using the data in https://github.com/ktye/qr/blob/master/qr_test.go#L26 , the calculated $A @ x$ is different from $b$.
In fact:

The values for $A @ x$ and $b$ are:
```
index    A @ x                                                                        b
0          (0.05789248367631611-0.7022254128981402i)      (-0.44376691010502084-1.0850980967217192i)
1          (-0.971782844762282-0.8393701968448928i)         (-1.3225296477428206-0.7071585907609175i)
2          (-1.2290606593049305+0.05488399541885913i)    (-0.8595211662220443-0.30165454575481065i)
3          (-0.8753196601799194-0.4856287901231674i)       (-1.4130011724760672-1.2004405038004398i)
4          (-1.1962518505079123-0.01614802306172436i)     (-0.5159859003619162-0.019362266242742187i)
```

**Comment by ktye** [comment]
the system is overdetermined: A has more rows than columns.
there is no x which can satisfy Ax=b exactly.
But you can test for equality with a square system, e.g. 5x5.
Take any 5x5 matrix A, multiply with a random vector x (length 5) to get b, and test if LeastSquareSolve(A,b) is x.

**Comment by fumin** [comment]
I see, thanks for the clarification.
Just a suggestion, perhaps it would be helpful for `LeastSquareSolve` to return an error `errors.New("no solution")` in this case.
